/*
 * This source file was generated by the Gradle 'init' task
 */
package rpg;

import rpg.engine.common.Game;

import static javafx.application.Application.launch;

public class App {
  public static void main(String[] args) {
    System.setProperty("quantum.multithreaded", "true");
    launch(Game.class, args);
  }

}
