/*
 * This source file was generated by the Gradle 'init' task
 */
package rpg;

import rpg.engine.common.Game;

import static javafx.application.Application.launch;

public class App {
    public static void main(String[] args) {
        System.setProperty("quantum.multithreaded", "true");
        System.setProperty("prism.order", "es2,d3d");
        System.setProperty("prism.forceGPU","true");
        launch(Game.class, args);
    }

}
