package rpg.engine.monster;

public enum EnumMonsterKind {
    PLAYER,
    IGRENNE,
    SATYR,
    WEREWOLF,
    MINOTAUR,
    SKELETON_ARCHER,
    ORC_BERSERK,
    GORGON,
    PORTAL_CITY_HUB,
    PORTAL_LEVEL1,
    MINI_HEALTH_PICKUP,
    ELIXIR_OF_YOUTH,
    TREE,
    ROCK,
    BUSH,
    HOUSE,
    VILLAGER,
    LASER_CANNON_UP,
    LASER_CANNON_DOWN,
    LASER_CANNON_RIGHT,
    LASER_CANNON_LEFT
}

